### ISSUE TITLE
Mollie certificate problem 

### ISSUE THREAD

**Issue by Raymondsnijders** [thephpleague/omnipay-mollie#73] opened 2019-12-14 09:14 UTC
Since Mollie renewed their certificate on December 12th there is a problem with Aimeos. The error message is curl 60 local issuer certificate error.
How to fix this. All certificates on the server are up to date. Only Aimeos webshops has this error. Others still works like Multishop.

**Comment by w00tland** [comment] 2019-12-19 09:07
I have the same issue. On quite a few webshops using Mollie.

**Comment by barryvdh** [comment] 2019-12-28 21:10
Can this be fixed with updating your cacert files?

**Comment by Raymondsnijders** [comment] 2019-12-28 21:10
Hallo,

In verband met de feestdagen zijn wij vanaf 6 januari weer bereikbaar!

Met vriendelijke groet, 
Raymond Snijders 
Webshade

**Comment by barryvdh** [comment] 2019-12-28 21:11
Ping @judgej Ideas?

**Comment by Raymondsnijders** [comment] 2019-12-28 21:26
It has been solved by replacing de cacert file. I couldn't find it where it was saved in the first place. I received from Mollie a new cacert.pem file. Met vriendelijke groet, Raymond Snijders -------- Oorspronkelijk bericht --------Onderwerp: Re: [thephpleague/omnipay-mollie] Mollie certificate problem  (#73)Van: "Barry vd. Heuvel" Aan: thephpleague/omnipay-mollie Cc: Raymondsnijders ,Author Ping @judgej Ideas?

**Comment by willemstuursma** [comment] 2020-01-07 15:24
We solved this in most cases by shipping a `cacert.pem` file with the libraries or adding `composer/ca-bundle` to the dependencies. 

Many servers don't have an up to date list of root certificates.

**Comment by barryvdh** [comment] 2020-01-07 18:10
I encountered this issue with the v2 version of this gateway, because guzzle3 ships its own cacert, which is out of date. In that case the http client for omnipay must set the cacert to a different path (eg the composer bundle or system value)

**Closed by barryvdh** 2020-01-07 18:10 UTC

**Comment by rolradio** [comment] 2020-07-24 16:35
We have the same problem here, I read here that the problem is due to the cacert.pem
But I don't read how and if we can fix this problem.
Can someone give me a solution for this?

**Comment by Raymondsnijders** [comment] 2020-07-24 16:35
Hallo,

In verband met vakantie zijn wij gesloten. Behoeft uw mail beantwoording? Dan kunnen wij u vanaf maandag 17 augustus hierop bericht doen.

Met vriendelijke groet, 
Raymond Snijders 
Webshade

**Comment by barryvdh** [comment] 2020-07-27 08:06
The best way is to upgrade to the latest version of Omnipay (v3) and this gateway.
You could try updating composer/ca-bundle or install that package and create your Http Client using a custom `verify` path for the CA Cert: \Composer\CaBundle\CaBundle::getBundledCaBundlePath()
